schema_version: 1

context:
  name: boxsdk
  version: "10.17.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/boxsdk-${{ version }}.tar.gz
  sha256: fe42658185901b80437a0d5b393c91b4a732f3b78d1be11d881aa7484807c9d5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - requests-toolbelt

tests:
  - python:
      imports:
        - box_sdk_gen
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Official Box Python SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/box/box-python-sdk
  documentation: https://pythonhosted.org/boxsdk/

extra:
  recipe-maintainers:
    - akrherz
